PackageIdentifier: Hxmbl.everything
PackageVersion: 0.1.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: everything.exe
    PortableCommandAlias: everything
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Hxmbl/everything/releases/download/v0.1.0/everything_0.1.0_Windows_x86_64.zip
    InstallerSha256: 5e78497c195a41daa6847dc20f3c83c0c3cb1649edcdd8c616bc023e81590b32
ManifestType: installer
ManifestVersion: 1.6.0
